apiVersion: v2
name: homepage
description: A Helm chart for deploying the Spitikos Next.js homepage.
type: application
version: 0.1.0
appVersion: 1.0.0
icon: "https://raw.githubusercontent.com/spitikos/spitikos/main/assets/icon.svg"
annotations:
  charts.helm.sh/display-name: "Homepage"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../_common"
