replicaCount: 1

image:
  repository: ghcr.io/spitikos/homepage
  pullPolicy: Always
  tag: 59984b1b572019ded32a063cd07abcd36a299776

service:
  type: ClusterIP
  port: 80
  containerPort: 3000
  portName: http

ingress:
  enabled: true
  host: spitikos.dev
  scheme: http

