apiVersion: v2
name: vault-wrapper
description: A wrapper Helm chart for the Hashicorp Vault chart.
type: application
version: 0.30.1
appVersion: 1.20.1
icon: "https://raw.githubusercontent.com/spitikos/.github/main/assets/icon.svg"
annotations:
  charts.helm.sh/display-name: "Vault"

dependencies:
  - name: vault
    version: 0.30.1
    repository: "https://helm.releases.hashicorp.com"
