apiVersion: v2
name: prometheus-wrapper
description: A wrapper Helm chart for the kube-prometheus-stack chart.
type: application
version: 0.1.0
appVersion: v0.83.0
icon: "https://raw.githubusercontent.com/spitikos/spitikos/main/assets/icon.svg"
annotations:
  charts.helm.sh/display-name: Prometheus

dependencies:
  - name: kube-prometheus-stack
    version: 75.18.1
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: common
    version: "0.1.0"
    repository: "file://../_common"
