apiVersion: v2
name: ingress-nginx-wrapper
description: A wrapper Helm chart for the official ingress-nginx chart.
type: application
version: 0.1.0
appVersion: 1.13.1
icon: "https://raw.githubusercontent.com/spitikos/spitikos/main/assets/icon.svg"
annotations:
  charts.helm.sh/display-name: "NGINX Ingress Controller"

dependencies:
  - name: ingress-nginx
    version: "4.10.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
