apiVersion: v2
name: api
description: A Helm chart for the Spitikos Monolithic API Server.
type: application
version: 0.1.0
appVersion: 1.0.0
icon: "https://raw.githubusercontent.com/spitikos/spitikos/main/assets/icon.svg"
annotations:
  charts.helm.sh/display-name: "API"
