{{- include "common.deployment" . | nindent 0 }}
---
{{- include "common.service" . | nindent 0 }}
---
{{- include "common.ingress" . | nindent 0 }}
---
{{- include "common.configmap" . | nindent 0 }}
---
{{- include "common.scaledobject" . | nindent 0 }}

