apiVersion: v2
name: argocd
description: A Helm chart for deploying the Argo CD App of Apps pattern.
type: application
version: 0.1.0
appVersion: v3.1.0
icon: "https://raw.githubusercontent.com/spitikos/.github/main/assets/icon.svg"
annotations:
  charts.helm.sh/display-name: "Argo CD Apps"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../_common"
