# This is a sample values.yaml file for the _common library chart.
# It is intended for documentation purposes to show all available fields.
# Application charts should override these values in their own values.yaml.

deployment:
  replicaCount: 1
  image:
    repository: ""
    pullPolicy: Always
    tag: ""
  imagePullSecrets: []
  resources: {}
   # requests:
   #   cpu: 100m
   #   memory: 128Mi
   # limits:
   #   cpu: 500m
   #   memory: 256Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  portName: http

ingress:
  host: ""
  className: "nginx"
  annotations: {}
  serviceName: ""
  servicePort: 0

configmap:
  mountDir: ""
  filename: ""
  data: ""

scaledobject:
  minReplicas: 0
  maxReplicas: 5
  pollingInterval: 30
  cooldownPeriod: 300
  prometheus:
    query: ""
    threshold: "10"